/** Extracted from the user’s 탭투톡체.svg; square viewBoxes rotate around the artwork center. */
export const GLYPH_ASSETS: Readonly<Record<string, { url: string }>> = {
  "ㄱ": { url: "/assets/glyphs/talk-type/u3131.svg" },
  "ㄴ": { url: "/assets/glyphs/talk-type/u3134.svg" },
  "ㄷ": { url: "/assets/glyphs/talk-type/u3137.svg" },
  "ㄹ": { url: "/assets/glyphs/talk-type/u3139.svg" },
  "ㅁ": { url: "/assets/glyphs/talk-type/u3141.svg" },
  "ㅂ": { url: "/assets/glyphs/talk-type/u3142.svg" },
  "ㅅ": { url: "/assets/glyphs/talk-type/u3145.svg" },
  "ㅇ": { url: "/assets/glyphs/talk-type/u3147.svg" },
  "ㅈ": { url: "/assets/glyphs/talk-type/u3148.svg" },
  "ㅊ": { url: "/assets/glyphs/talk-type/u314a.svg" },
  "ㅋ": { url: "/assets/glyphs/talk-type/u314b.svg" },
  "ㅌ": { url: "/assets/glyphs/talk-type/u314c.svg" },
  "ㅍ": { url: "/assets/glyphs/talk-type/u314d.svg" },
  "ㅎ": { url: "/assets/glyphs/talk-type/u314e.svg" },
  "ㅱ": { url: "/assets/glyphs/talk-type/u3171.svg" },
  "△": { url: "/assets/glyphs/talk-type/u25b3.svg" },
  "ㆁ": { url: "/assets/glyphs/talk-type/u3181.svg" },
  "ㆆ": { url: "/assets/glyphs/talk-type/u3186.svg" },
  "ㆀ": { url: "/assets/glyphs/talk-type/u3180.svg" },
  "ㅍ-stem-one": { url: "/assets/glyphs/talk-type/u314d-stem-one.svg" },
  "ㅍ-stem-three": { url: "/assets/glyphs/talk-type/u314d-stem-three.svg" },
  "ㅣ": { url: "/assets/glyphs/talk-type/u3163.svg" },
  "ㅡ": { url: "/assets/glyphs/talk-type/u3161.svg" },
  "ㆍ": { url: "/assets/glyphs/talk-type/u318d.svg" },
  "★": { url: "/assets/glyphs/talk-type/u2605.svg" },
  ",": { url: "/assets/glyphs/talk-type/u002c.svg" },
  "♥": { url: "/assets/glyphs/talk-type/u2665.svg" },
  "╱": { url: "/assets/glyphs/talk-type/u2571.svg" },
  "╲": { url: "/assets/glyphs/talk-type/u2572.svg" },
  "!": { url: "/assets/glyphs/talk-type/u0021.svg" },
  "?": { url: "/assets/glyphs/talk-type/u003f.svg" },
  "○": { url: "/assets/glyphs/talk-type/u3147.svg" },
};
