"""Freeze the three intro labels as serif outlines, avoiding webfont swaps."""
from pathlib import Path
import json
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.transformPen import TransformPen

root = Path(__file__).resolve().parents[1]
font = instantiateVariableFont(TTFont(root / 'font/NotoSerifKR-VariableFont_wght.ttf'), {'wght': 700})
glyphs = font.getGlyphSet()
cmap = font.getBestCmap()
marks = {}
for mode, text, size in [('alphabet', 'ㄱ', 72), ('syllable', '가', 72), ('word', '강', 72)]:
    pen = SVGPathPen(glyphs)
    bounds = BoundsPen(glyphs)
    advance = 0
    for char in text:
        glyph = glyphs[cmap[ord(char)]]
        transform = (1, 0, 0, 1, advance, 0)
        glyph.draw(TransformPen(pen, transform))
        glyph.draw(TransformPen(bounds, transform))
        advance += glyph.width
    x0, y0, x1, y1 = bounds.bounds
    scale = size / font['head'].unitsPerEm
    x = 70 - (x0 + x1) * scale / 2
    y = 70 + (y0 + y1) * scale / 2
    marks[mode] = f'<svg viewBox="0 0 140 140" aria-hidden="true"><path fill="currentColor" transform="translate({x} {y}) scale({scale} {-scale})" d="{pen.getCommands()}"/></svg>'
(root / 'src/config/introMarks.ts').write_text('// Generated by scripts/build-intro-marks.py from bundled Noto Serif KR 700.\nexport const INTRO_MARKS = ' + json.dumps(marks, ensure_ascii=False) + ' as const;\n')
